apiVersion: v1
kind: Service
metadata:
  name:  trend-deploy-service
  namespace: trend
spec:
  type: NodePort
  selector:
    app: trend-deploy
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
